version: "3.9"   
services:

  db:
    container_name: django_admin_db
    image: postgres:14.5
    
    restart: always
    env_file:
      - .env
    networks:
      - djangonetwork

  admin_api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
      
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    
networks:
      djangonetwork:
          driver: bridge
      

